name: CI

on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Update toolchain
            run: |
              rustup update
              rustup component add clippy

          - name: Lint
            run: |
              cargo fmt -- --check
              cargo clippy -- -D warnings

          - name: Test
            run: |
              cargo check
              cargo test --all

          - name: Build
            run: cargo build --release
